### ISSUE TITLE
[BUG] Bot randomly leaves

### ISSUE THREAD

**Issue by FreshImmuc** [codebois-dev/bard#8]
**Describe the bug**
When a song is over and there **are more** in queue, the bot sometimes just randomly leaves.
This also occurs when a new song is started from the search bar when the bot is not in a voice channel. Sometimes, the song gets added, the  bot joins and it instantly disconnects again. The song is also removed from the queue.

**To Reproduce**
Well have a queue, skip some songs and it sometimes happens but not every time.

**Screenshots**
/

**Host machine (please complete the following information):**
OS: Windows, NodeJS v16

**Client machine (please complete the following information):**
- Discord

**Comment by MaciejkaG** [comment]
Possible solutions described in #1 (like changing used YTDL library). If those won't work then unfortunately I can't help as it's an error on the [discord-player](https://github.com/Androz2091/discord-player)/FFmpeg/YouTube DL module side.
